### ISSUE TITLE
左边的那个点一下  弹出来一个小静态列表，我怎么在代码中实现不了啊

### ISSUE THREAD

**Issue by h824612113** [maltsugar/CustomPopoverView#3]
按照你的代码，leftButton实现的内容变成了右边button实现的内容“I'm viewController's view”；我看你的动态图不是应该实现了左上角点一下弹出一个静态列表吗？请问是怎么回事啊？

还有，你之前做的demo是在UIViewController+导航的基础上实现的，我换成UITableView+导航会不会有影响 啊？
应该是我的Xcode的版本低，所以运行不了，7.2的，我是直接拖你的代码用的。求解惑

**Comment by maltsugar** [comment]
应该不会有问题的，showFrom会根据你的触发按钮，决定弹出视图的位置。你如果想按钮和弹出视图左对齐，对其方式设置CPAlignStyleLeft就行了。
你可以把你的需求再描述下，是点击左边的按钮弹出一组菜单  还是 弹一个自定义VC？

**Comment by maltsugar** [comment]
点击左边的按钮弹出一组菜单

<pre><code>
_titles = @[@"Menu1", @"Menu2", @"Ah_Menu3"];
CustomPopOverView *view = [[CustomPopOverView alloc]initWithBounds:CGRectMake(0, 0, 120, 44*3) titleMenus:_titles];;
view.containerBackgroudColor = [UIColor blueColor];
view.delegate = self;
[view showFrom:_leftBtn alignStyle:CPAlignStyleLeft];
</code></pre>

你可以改里面cell的样式，周围空隙。
我写那几种demo，看不懂吗😪
