### ISSUE TITLE
iOS 11 弹不出来

### ISSUE THREAD

**Issue by CoderJayLuo** [maltsugar/CustomPopoverView#5]
[view showFrom:_button alignStyle:CPAlignStyleCenter];
这句话在iOS11中不起作用, 弹不出来

**Comment by maltsugar** [comment]
你好 我下载下来  demo运行正常，你是怎么写的？
![](http://wx3.sinaimg.cn/mw690/72aba7efly1fkd6849ncjj20ge10q75r.jpg)
