### ISSUE TITLE
iOS 11 失效

### ISSUE THREAD

**Issue by LiWangWu** [maltsugar/CustomPopoverView#6]
点击无反应 调试是没有走cellForRow 方法

**Comment by maltsugar** [comment]
很抱歉给你带来不便，demo跑在iOS11 是没有问题的。请问你的是不出现还是出现点击无反应，你可以调试下视图，看下frame

**Comment by maltsugar** [comment]
刚发现无法弹出的问题，兄弟更新下 试试

**Comment by LiWangWu** [comment]
好的 感谢你能这么尽心尽力的维护并解决我们在使用中遇到的问题 分享精神可贵 感谢！
