### ISSUE TITLE
view大小和屏幕同宽就出问题了

### ISSUE THREAD

**Issue by czl0325** [maltsugar/CustomPopoverView#7]
当你把弹出的popupview宽度设置成和屏幕一样宽，就出问题了。例如改你demo的源码如下：

注意黑色粗体部分：
`- (void)optionClick:(UIButton *)sender
{
    NSArray *menus = @[@"清空已完成", @"清空全部"];
    CustomPopOverView *pView = [[CustomPopOverView alloc]initWithBounds:**CGRectMake(0, 0, [UIScreen mainScreen].bounds.size.width, 300)** titleMenus:menus config:nil];
    pView.delegate = self;
    pView.containerBackgroudColor = RGBCOLOR(64, 64, 64);
    [pView showFrom:sender alignStyle:CPAlignStyleRight];
}

//或者

- (void)handleLeftClick {
    UIViewController *vc = [[UIViewController alloc]init];
    vc.view.backgroundColor = [UIColor yellowColor];
    vc.view.frame = CGRectMake(0, 0, **[UIScreen mainScreen].bounds.size.width**, 300);
    UILabel *lab = [[UILabel alloc]initWithFrame:CGRectMake(0, 0, 140, 100)];
    lab.center = vc.view.center;
    lab.text = @"I'm viewController's view";
    lab.numberOfLines = 0;
    [vc.view addSubview:lab];
    CustomPopOverView *view = [CustomPopOverView popOverView];
    view.contentViewController = vc;
    [view showFrom:_leftBtn alignStyle:CPAlignStyleLeft];
}`

**Comment by maltsugar** [comment]
感谢反馈，这种宽度和屏幕一样时，需要定义config 四周的间隙为0。不然默认会有间隙。
我的代码问题是如果只设置config某些值，未设置行高，会导致tableView 行高为0。 现在已修改，再次感谢

**Comment by czl0325** [comment]
还是不行，我在你demo上的- (void)optionClick:(UIButton *)sender函数写的，你看看

- (void)optionClick:(UIButton *)sender
{
    
    NSArray *menus = @[@"清空已完成", @"清空全部"];
//    CGRectMake(0, 0, [UIScreen mainScreen].bounds.size.width, 300)
    PopOverVieConfiguration *config = [PopOverVieConfiguration new];
    config.triAngelHeight = 8.0;
    config.triAngelWidth = 10.0;
    config.containerViewCornerRadius = 10.0;
    config.roundMargin = 0;
    config.showSpace = 0;
    
    
    CustomPopOverView *pView = [[CustomPopOverView alloc]initWithBounds:CGRectMake(0, 0, [UIScreen mainScreen].bounds.size.width, 300) titleMenus:menus config:config];
    pView.delegate = self;
    pView.containerBackgroudColor = RGBCOLOR(64, 64, 64);
    [pView showFrom:**sender** alignStyle:CPAlignStyleRight];_//这个黑体部分，注意你要传入sender_
   
}

**Comment by czl0325** [comment]
设置成与屏幕同宽，然后把sender传进去，不能传nil

**Comment by czl0325** [comment]
你看看PopOverVieConfiguration的配置对吗？

**Comment by maltsugar** [comment]
现在可以了 你可以试下。 宽度和屏幕一样时，只是建议把PopOverVieConfiguration 设置下四周间隙为0，不然肯定会超出一点。如果sender不传就是居中显示，居中显示时建议 小三角宽高设置为0

**Comment by maltsugar** [comment]
你重新下载啊  直接可以跑

**Comment by czl0325** [comment]
![1](https://user-images.githubusercontent.com/2100549/33004771-934cbcfe-cdfd-11e7-9d57-a138cab4a67a.png)

奇怪，你不会出现这种情况吗？

**Comment by maltsugar** [comment]
这种情况宽度也不能是屏幕宽度，因为弹出视图和按钮右对齐。你视图宽度，最大为屏幕宽度-按钮离屏幕右边的空隙- 2*四周间隙

**Comment by maltsugar** [comment]
之前是 cell直接没出来，因为高度为0了

**Comment by maltsugar** [comment]
这种情况宽度也不能是屏幕宽度，因为弹出视图和按钮右对齐。你视图宽度，最大为屏幕宽度-按钮离屏幕右边的空隙- 2*四周间隙。 如果你用这个按钮左对齐，那么留给视图宽度将会更窄，需要自己衡量的

**Comment by czl0325** [comment]
还有一个问题，你是加在windows上的，如果点击你view里面的cell触发一个弹框事件，会导致你的CustomPopOverView被销毁，如何让他还是存在呢？

**Comment by maltsugar** [comment]
声明成全局的，让VC强引用
